name: banking_app
description: "Created banking app for Financial Banking purpose"


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/
  
